[package]
name = "git-repo-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", default-features = false, features = [
    "std",
    "color",
    "derive",
    "help",
    "usage",
] }
path-slash = "0.2"
walkdir = "2.4"

[profile.release]
strip = true
